apiVersion: kobe.semagrow.org/v1alpha1
kind: Experiment
metadata:
  name: geographica-synth-exp
spec:
  benchmark: geographica-synthetic
  federatorName: uno-synth
  federatorTemplateRef: unotemplate
  evaluator:
    image: semagrow/kobe-sequential-evaluator
  timesToRun: 3
  dryRun: false
  forceNewInit: false
