apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: benchmarks.kobe.semagrow.org
spec:
  group: kobe.semagrow.org
  names:
    kind: Benchmark
    listKind: BenchmarkList
    plural: benchmarks
    singular: benchmark
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: Benchmark is the Schema for the benchmarks API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: BenchmarkSpec defines the components for this benchmark setup
          properties:
            datasets:
              items:
                type: string
              type: array
            queries:
              items:
                description: Query contains the query info
                properties:
                  language:
                    type: string
                  name:
                    type: string
                  queryString:
                    type: string
                required:
                - language
                - name
                - queryString
                type: object
              type: array
          required:
          - datasets
          - queries
          type: object
        status:
          description: BenchmarkStatus defines the observed state of Benchmark
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
