apiVersion: kobeexperiment.kobe.com/v1alpha1
kind: KobeExperiment
metadata:
  name: kobeexp1
spec:
  benchmark: kobebenchmark1
  federator: semagrow
  timesToRun: 1
  dryRun: true
  forceNewInit: false
  evalImage: nginx
