apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: kobedatasets.kobedataset.kobe.com
spec:
  group: kobedataset.kobe.com
  names:
    kind: KobeDataset
    listKind: KobeDatasetList
    plural: kobedatasets
    singular: kobedataset
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: KobeDataset is the Schema for the kobedatasets API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            count:
              format: int32
              type: integer
            downloadFrom:
              type: string
            env:
              items:
                properties:
                  name:
                    description: 'INSERT ADDITIONAL STATUS FIELD - define observed
                      state of cluster Important: Run "operator-sdk generate k8s"
                      to regenerate code after modifying this file Add custom validation
                      using kubebuilder tags: https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html'
                    type: string
                  value:
                    type: string
                required:
                - name
                - value
                type: object
              type: array
            forceLoad:
              type: boolean
            group:
              type: string
            image:
              description: 'INSERT ADDITIONAL SPEC FIELDS - desired state of cluster
                Important: Run "operator-sdk generate k8s" to regenerate code after
                modifying this file Add custom validation using kubebuilder tags:
                https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html'
              type: string
            imagePullPolicy:
              description: PullPolicy describes a policy for if/when to pull a container
                image
              type: string
            port:
              format: int32
              type: integer
            sparqlEnding:
              type: string
          required:
          - count
          - downloadFrom
          - env
          - forceLoad
          - group
          - image
          - imagePullPolicy
          - port
          - sparqlEnding
          type: object
        status:
          description: KobeDatasetStatus defines the observed state of KobeDataset
          properties:
            appgroup:
              type: string
            podnames:
              description: 'INSERT ADDITIONAL STATUS FIELD - define observed state
                of cluster Important: Run "operator-sdk generate k8s" to regenerate
                code after modifying this file Add custom validation using kubebuilder
                tags: https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html'
              items:
                type: string
              type: array
          required:
          - appgroup
          - podnames
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
