{{- if and .Values.enabled .Values.global.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "kobe-operator.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ template "kobe-operator.name" . }}
    app.kubernetes.io/instance:  {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ template "kobe-operator.chart" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "kobe-operator.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "kobe-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}