apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "kobe-operator.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ template "kobe-operator.name" . }}
    app.kubernetes.io/name: {{ template "kobe-operator.name" . }}
    app.kubernetes.io/instance:  {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ template "kobe-operator.chart" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "kobe-operator.name" . }}
      app.kubernetes.io/name: {{ template "kobe-operator.name" . }}
      app.kubernetes.io/instance:  {{ .Release.Name }}
      app.kubernetes.io/managed-by: {{ .Release.Service }}
    template:
    metadata:
      labels:
        app: {{ template "kobe-operator.name" . }}
        app.kubernetes.io/name: {{ template "kobe-operator.name" . }}
        app.kubernetes.io/instance:  {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        helm.sh/chart: {{ template "kobe-operator.chart" . }}
{{- if .Values.podLabels }}
{{ toYaml .Values.podLabels | indent 8 }}
{{- end }}
      annotations:
      {{- if .Values.podAnnotations }}
{{ toYaml .Values.podAnnotations | indent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ template "kobe-operator.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: {{ template "kobe-operator.image" | quote }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: WATCH_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: OPERATOR_NAME
            value: {{ template "kobe-operator.fullname" . }}
        {{- if .Values.extraEnv }}
{{ toYaml .Values.extraEnv | indent 10 }}
        {{- end }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}