apiVersion: kobe.semagrow.org/v1alpha1
kind: KobeDataset
metadata:
  name: kegg
spec:
  # Add fields here
  image: kostbabis/virtuoso
  forceLoad: false
  downloadFrom: http://users.iit.demokritos.gr/~gmouchakis/dumps/KEGG.tar.gz
  replicas: 1
  port: 8890
