apiVersion: kobe.semagrow.org/v1alpha1
kind: DatasetTemplate
metadata:
  name: virtuosotemplate
spec:
  initContainers:
    - name: initcontainer0
      image: antru6/url-downloader
    - name: initcontainer1
      image: antru6/virtuoso-init
  containers:
    - name: maincontainer
      image: antru6/virtuoso-main
      ports:
        - containerPort: 8890
  port: 8890
  path: /sparql
  initPolicy: ForceInit

