apiVersion: kobe.semagrow.org/v1alpha1
kind: Benchmark
metadata:
  name: toybench
spec:
  datasets:
    - name: toy1
      files:
        -url: http://users.iit.demokritos.gr/~antru/dumps/toy1.tar.gz
      templateRef: virtuosotemplate
      networkTopology: 
        - datasetSource: toy1
          delayInjection:
            fixedDelaySec: 1
            percentage: 100
      federatorConnection:
         delayInjection:
           fixedDelaySec: 2
           fixedDelayMSec: 100
           percentage: 100
   - name: toy2
     files:
       -url: http://users.iit.demokritos.gr/~antru/dumps/toy2.tar.gz
     templateRef: virtuosotemplate
     federatorConnection:
        delayInjection:
          fixedDelaySec: 2
          percentage: 100
  queries:
    - name: tq1
      language: sparql
      queryString: "SELECT * WHERE {
  <http://example.org/33> <http://www.w3.org/2002/07/owl#sameAs> ?o .
  ?o <http://purl.org/dc/terms/creator> ?c .
  ?o <http://example.org/value> ?v .
}"
    - name: tq2
      language: sparql
      queryString: "SELECT * WHERE {
  ?o <http://purl.org/dc/terms/creator> <http://semagrow.org/antru> .
  ?s <http://www.w3.org/2002/07/owl#sameAs> ?o .
}"
    - name: tq3
      language: sparql
      queryString: "SELECT * WHERE {
  ?s <http://www.w3.org/2002/07/owl#sameAs> ?o .
  ?o <http://example.org/value> ?v .
  FILTER (?v > 33)
}"

  OPTIONAL { $drug <http://www4.wiwiss.fu-berlin.de/drugbank/resource/drugbank/biotransformation> $transform . } 
}"
