apiVersion: kobe.semagrow.org/v1alpha1
kind: Experiment
metadata:
  name: fedx-cd-exp
spec:
  benchmark: fedbench-crossdomain
  federatorName: fedx-cd
  federatorTemplateRef: fedxtemplate
  evaluator:
    image: semagrow/kobe-sequential-evaluator
  timesToRun: 3
  dryRun: false
  forceNewInit: false 

